version: '3.7'

services:
  lychee:
    image: linuxserver/lychee
    container_name: lychee
    volumes:
      - ./volumes/lychee/conf:/conf
      - ./volumes/lychee/uploads:/uploads
    networks:
      - proxy
    env_file:
      - configuration/lychee/lychee.env
    restart: unless-stopped
