version: '3.7'
services:
  ipa:
    build:
      context: ./FreeIPA/master/
      dockerfile: Dockerfile
    image: ipa-master:latest
    volumes:
        - /var/lib/ipa-master-data:/data:Z
        - /var/lib/ipa-master-data/journal:/run/log/journal:Z
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - /dev/urandom:/dev/random:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    hostname: ipa
    domainname: ubercore.local
    stop_signal: RTMIN+3
    env_file:
      - ipa.master.env
    restart: unless-stopped
    networks:
      - ipa
    ports:
      - "53:53"         # dns bind
      - "53:53/udp"     # dns bind
      - "88:88"         # kerberos
      - "88:88/udp"     # kerberos
      - "123:123/udp"   # ntp
      - "389:389"       # ldap directory service
      - "636:636"       # ldaps directory service
      - "464:464"       # kerberos authentication
      - "464:464/udp"   # kerberos authentication
      - "7389:7389"     # dogtag PKI-CA: Directory Service
      - "9443:9443"     # Recplica configuration
      - "9444:9444"     # Recplica configuration
      - "9445:9445"     # Recplica configuration

  haproxy:
    build:
      context: ./HAProxy/
      dockerfile: Dockerfile
    image: haproxy:latest
    volumes:
      - ./configuration/haproxy/ubercore.local.pem:/etc/ssl/ubercore.local.pem:ro
    networks:
      - core
      - proxy
      - ipa
    ports:
      - "80:80"
      - "443:443"
    environment:
      SYSLOGD: 1
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/mssql:/var/lib/mysql
    env_file:
      - configuration/mssql/mssql.env
    networks:
      - mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - proxy
      - mysql

networks:
  proxy:
  mysql:
  ipa: